/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

rootProject.name = "SNT"

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://maven.scijava.org/content/repositories/releases")
    }
}

dependencyResolutionManagement {

    repositories {
        maven("https://maven.scijava.org/content/repositories/releases")
    }
    versionCatalogs {
        create("libs").from("org.scijava:gradle-catalog:0.11")
        create("platforms").library("scijava", "org.scijava:gradle-platform:0.13")

        // fails with "Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'."
        //        create("libs").from(files("../pom-scijava/gradle/catalog/build/version-catalog/libs.versions.toml"))
    }

    //    includeBuild("../pom-scijava/gradle/catalog")
    // java-ecosystem-capabilities
    //    includeBuild("../../../java-ecosystem-capabilities")
}